const SEARCH_RESULTS = [
    { tags: 'apple fruit', title: 'Apple - Wikipedia', description: 'An apple is an edible fruit produced by an apple tree (Malus domestica).', url: 'https://en.wikipedia.org/wiki/Apple'},
    { tags: 'apples market', title: 'Apples Market: Home', description: 'fbpx. A theme logo of Apples Market. Basket0. Reorder. My Store: Select Store · Select Another Store · Welcome, |My Account Sign In|Create an Account.', url: 'https://www.applesmarket.com/'},
    { tags: 'apple juices', title: 'How to Make Apple Juice (With and Without Juicer)', description: 'Make apple juice (unfiltered apple cider juice) at home with a blender, juicer, or manual, with no added sugar.', url: 'https://www.alphafoodie.com/how-to-make-apple-juice/'},
    { tags: 'apple juice recipe', title: 'Homemade Apple Juice Recipe - Tablespoon.com', description: '1. Start by washing and then coring the apple to remove seeds. · 2. Add the apples to the pot and add enough water to just cover them. · 3. Slowly boil the apples.', url: 'https://www.tablespoon.com/recipes/homemade-apple-juice/bcf44468-1eed-479a-88d6-2bd4c3cfacd3'},
    { tags: 'apple juice shop', title: 'OWASP Juice Shop', description: 'Apple Juice (1000ml). 1.99¤. Apple Pomace. 0.89¤. Banana Juice (1000ml). 1.99¤. Only 1 left. Best Juice Shop Salesman Artwork. 5000¤. Carrot Juice (1000ml).', url: 'https://juice-shop.herokuapp.com/#/'},
    { tags: 'apple pie', title: 'Apple Pie by Grandma Ople Recipe - Allrecipes', description: ' Ingredients ; 8 small Granny Smith apples, or as needed ; 3 tablespoons all-purpose flour ; ½ cup white sugar ; ½ cup packed brown sugar.', url: 'https://www.allrecipes.com/recipe/12682/apple-pie-by-grandma-ople/'},
    { tags: 'apple pie dessert', title: 'Perfect Apple Pie Recipe - Pillsbury.com', description: 'Filling* ; 6 cups thinly sliced, peeled apples (6 medium) ; 3/4 cup sugar ; 2 tablespoons all-purpose flour ; 3/4 teaspoon ground cinnamon.', url: 'https://www.pillsbury.com/recipes/perfect-apple-pie/1fc2b60f-0a4f-441e-ad93-8bbd00fe5334'},
    { tags: 'apple pie recipe', title: 'Apple Pie Recipe with the Best Filling (VIDEO)', description: 'Ingredients ; 1 recipe for double pie crust ; 2 1/4 lbs Granny Smith Apples, peeled, cored 6-7 apples (7 cups thinly sliced).', url: 'https://natashaskitchen.com/apple-pie-recipe/'},

    { tags: 'batman', title: 'Batman - Wikipedia', description: 'Batman is a superhero appearing in American comic books published by DC Comics. The character was created by artist Bob Kane and writer Bill Finger', url: 'https://en.wikipedia.org/wiki/Batman'},
    { tags: 'batman movie', title: 'The Batman (film) - Wikipedia', description: 'The Batman is a 2022 American superhero film based on the DC Comics character Batman. Produced by DC Films, 6th & Idaho, and Dylan Clark Productions.', url: 'https://en.wikipedia.org/wiki/The_Batman_(film)'},
    { tags: 'batman movie online', title: 'Watch The Batman Streaming Online | Hulu (Free Trial)', description: 'Start your free trial to watch The Batman and other popular TV shows and movies including new releases, classics, Hulu Originals, and more.', url: 'https://www.hulu.com/movie/the-batman-54faddb3-3315-4e1f-9f86-3d55409831db'},
    { tags: 'batman movie release date', title: 'The Batman: Release date for movie theaters and streaming', description: 'After multiple production delays and release date changes amid the coronavirus, The Batman is set to hit theaters on March 4, 2022. Find out everything you need to know about the latest Batman installment below.', url: 'https://www.marca.com/en/lifestyle/movies/2022/02/27/621bc86c268e3ef53c8b45b9.html'},
    { tags: 'batman arkham', title: 'Batman: Arkham - Wikipedia', description: 'Batman: Arkham is a series of action-adventure video games based on the DC Comics character Batman, developed by Rocksteady Studios and WB Games.', url: 'https://en.wikipedia.org/wiki/Batman:_Arkham'},
    { tags: 'batman arkham asylum', title: 'Batman: Arkham Asylum Game of the Year Edition on Steam', description: 'Critically acclaimed Batman: Arkham Asylum returns with a remastered Game of the Year Edition, featuring 4 extra Challenge Maps.', url: 'https://store.steampowered.com/app/35140/Batman_Arkham_Asylum_Game_of_the_Year_Edition/'},
    { tags: 'batman arkham knight', title: 'titletitle', description: 'description', url: 'urllocation'},
    
    { tags: 'catwoman', title: 'Catwoman - Wikipedia', description: 'Catwoman is the alter ego of Selina Kyle, a Gotham City burglar who usually wears a tight, one-piece outfit and uses a bullwhip for a weapon.', url: 'https://en.wikipedia.org/wiki/Catwoman'},
    { tags: 'catwoman movie', title: 'Catwoman (film) - Wikipedia', description: 'Catwoman is a 2004 American superhero film loosely based on the DC Comics character Catwoman. It was directed by Pitof and written by John Rogers.', url: 'https://en.wikipedia.org/wiki/Catwoman_(film)'},
    { tags: 'catwoman movie cast', title: 'Full Cast & Crew - Catwoman (2004) - IMDb', description: 'Catwoman (2004) cast and crew credits, including actors, actresses, directors, writers and more.', url: 'https://www.imdb.com/title/tt0327554/fullcredits'},
    { tags: 'catwoman movie release date', title: 'Catwoman - Rotten Tomatoes', description: 'Movie Info ; Release Date (Streaming):. Jan 18, 2005 ; Box Office (Gross USA):. $40.2M ; Runtime: 1h 44m ; Distributor: Warner Bros. Pictures.', url: 'https://www.rottentomatoes.com/m/catwoman'},
    { tags: 'catwoman quotes', title: "25 Catwoman Quotes That'll Make You Feel Sultry - Women.com", description: "Life would be so much easier if I didn't have this conscience!", url: 'https://www.women.com/ashleyferraro/lists/catwoman-quotes-110419'},
    { tags: 'catwoman quotes 2022', title: 'The Batman (2022) - Zoë Kravitz as Selina Kyle - IMDb', description: 'Catwoman : What, do you live in a cave?', url: 'https://www.imdb.com/title/tt1877830/characters/nm2368789'},
    { tags: 'catwoman quotes arkham city', title: 'Catwoman - Arkham Wiki - Fandom', description: "Selina Kyle, also known by her alias Catwoman, was an orphan who learned to survive on Gotham City's streets. She took to thievery to survive.", url: 'https://arkhamcity.fandom.com/wiki/Catwoman'},

    { tags: 'react', title: 'React – A JavaScript library for building user interfaces', description: 'React · Declarative. React makes it painless to create interactive UIs. · Component-Based. Build encapsulated components that manage their own state.', url: 'https://reactjs.org/'},
    { tags: 'react js', title: 'React (JavaScript library) - Wikipedia', description: 'React (also known as React.js or ReactJS) is a free and open-source front-end JavaScript library for building user interfaces based on UI components.', url: 'https://en.wikipedia.org/wiki/React_(JavaScript_library)'},
    { tags: 'react js course', title: 'Courses - React', description: "Egghead.io: The Beginner's Guide to ReactJS - Free course for React newbies and those looking to get a better understanding of React fundamentals.", url: 'https://reactjs.org/community/courses.html'},
    { tags: 'react js tutorials', title: 'Tutorial: Intro to React', description: 'React is a declarative, efficient, and flexible JavaScript library for building user interfaces. It lets you compose complex UIs from small and isolated pieces.', url: 'https://reactjs.org/tutorial/tutorial.html'},
    { tags: 'react js tutorials free', title: 'React Tutorial: Learn React JS - Free 11-Hour Course', description: "Learn the basics of modern React by solving 140+ interactive coding challenges and building eight fun projects. What's inside. This course contains 151.", url: 'https://scrimba.com/learn/learnreact'},
    { tags: 'react js tutorials online', title: 'Learn React - Codecademy', description: 'In this React course, youll build powerful interactive applications with one of the most popular JavaScript libraries. Start. 404,638 learners enrolled.', url: 'https://www.codecademy.com/learn/react-101'},
    { tags: 'react js tutorials youtube', title: "Beginner's Tutorial for React JavaScript Library [2022]", description: 'Learn React by building eight real-world projects and solving 140+ coding challenges. You can also follow this course.', url: 'https://www.youtube.com/watch?v=bMknfKXIFA8&ab_channel=freeCodeCamp.org'},
    { tags: 'react native', title: 'React Native · Learn once, write anywhere', description: "React Native lets you create truly native apps and doesn't compromise your users' experiences. It provides a core set of platform agnostic native components.", url: 'https://reactnative.dev/'},
    { tags: 'react native tutorials', title: 'React Native Tutorial - Tutorialspoint', description: 'React Native Tutorial, React Native is a JavaScript framework for building native mobile apps. It uses the React framework.', url: 'https://www.tutorialspoint.com/react_native/index.htm'},
    { tags: 'react native support', title: 'Overview - React Native', description: "Needing and providing help. We expect all folks participating in React Native' communities to adhere to the guidelines within our Code.", url: 'https://reactnative.dev/community/overview'},
];
  
  export default SEARCH_RESULTS;