const SEARCH_RESULTS = [
  ["apple",
    [{ title: 'apple fruit title', description: 'apple fruit description', url: 'https://www.apple-fruite.com'}],
    [{ title: 'apples market title', description: 'apples market description', url: 'https://www.apples-market.com'}],
  ],

  ["apple juice",
    [{ title: 'apple juices title', description: 'apple juices description', url: 'https://www.apple-juice.com'}],
  ],

  ["apple juice recipe",
    [{ title: 'apple juice recipe title', description: 'apple juice recipe description', url: 'https://www.apple-juice.com'}],
  ],
  ["apple juice shop",
    [{ title: 'apple juice shop title', description: 'apple juice shop description', url: 'https://www.apple-juice.com'}],
  ],
  ["apple pie",
    [{ title: 'apple pie title', description: 'apple pie description', url: 'https://www.apple-juice.com'}],
  ],
  ["apple pie dessert",
    [{ title: 'apple pie dessert title', description: 'apple pie dessert description', url: 'https://www.apple-juice.com'}],
  ],
  ["apple pie recipe",
    [{ title: 'apple pie recipe title', description: 'apple pie recipe description', url: 'https://www.apple-juice.com'}],
  ],

  ["batman",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["batman movie",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["batman movie online",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["batman movie release date",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["batman arkham",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["batman arkham asylum",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["batman arkham knight",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],

  ["catwoman",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["catwoman movie",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["catwoman movie cast",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["catwoman movie release date",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["catwoman quotes",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["catwoman quotes 2022",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["catwoman quotes arkham city",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],

  ["react",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["react js",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["react js course",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["react js tutorials",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["react js tutorials free",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["react js tutorials online",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["react js tutorials youtube",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["react native",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["react native tutorials",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
  ["react native support",
    [{ title: 'web title', description: 'web description', url: 'https://www.apple-juice.com'}],
  ],
];
  
  export default AUTOCOMPLETE;